
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.mysql.example.com
  labels:
    api: kine-example
    apiserver: "true"
spec:
  version: v1
  group: mysql.example.com
  groupPriorityMinimum: 2000
  service:
    name: kine-example
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjVENDQWxtZ0F3SUJBZ0lKQUsyRlp2eG4ra0xhTUEwR0NTcUdTSWIzRFFFQkN3VUFNR3d4Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLekFwQmdOVkJBTU1JbXRwYm1VdFpYaGhiWEJzWlMxalpYSjBhV1pwWTJGMFpTMWhkWFJvCmIzSnBkSGt3SGhjTk1qQXhNREUwTVRBd016UXdXaGNOTWpFeE1ERTBNVEF3TXpRd1dqQnNNUXN3Q1FZRFZRUUcKRXdKMWJqRUxNQWtHQTFVRUNBd0NjM1F4Q2pBSUJnTlZCQWNNQVd3eENqQUlCZ05WQkFvTUFXOHhDekFKQmdOVgpCQXNNQW05MU1Tc3dLUVlEVlFRRERDSnJhVzVsTFdWNFlXMXdiR1V0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRkaW9sRlVEZytYNkREeHoKSG1yMjhtMTNJdndlYktQS3ppYlZFSDVDZktsWjVHb05HR3MvUUppaC8rK3hTVlVsMFhGRWt1NmpMY05ITEhXRQpIVlRyQ1NuejZSYWpMZ0FhL2RZN1dxYmtac2lwRDJNQmY3WEJrdW1NZGp2MlBXWVI2bUZtVHhVdDMrZzVyNVFHClNuMVBZMTI4M04xc1dtSXU1VHVzRHB2RTVLNkJHdUpnY2lmampEbngyb1R4ZXFOK0NrRU9UZkNoRCsrbUV6a3UKczNaYitONS8rVmpqZkxhTklBZ092Nk51d1Jsd0NNWW80Tk1LYis1Zk9LNlNYdTJNUi85dVdLQU5BM2YwdEh0ZAowc3JjTWU4KzZoSXFDNEI4N2lBSGpNTVJ3RzE2ZXJHbGtSRlhxNFJMSjBUR2k5dmR6K3pmakdGQ1NDZ0x6YUpRCi9LclBEd0lEQVFBQm94WXdGREFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUEwR0NTcUdTSWIzRFFFQkN3VUEKQTRJQkFRQnNIcGR1MG9CYy8xcnNNY0dzdi9aTE9WZzVaMldpVzdMVlYyNGlGK0hpcXZrSDJvNTFsSFRhY0JlbwpLeHQxM2xnMlI3VEViNklXeW8yS2tUeGJENVdwVHZDVEwrMHd1QWk5YVZMWmhNKzBPK0FLK2N5NzRnc2VMZktiClBHL0dZYm5jSVU5WlhweVdFT1F6RkUxcDdMTFVKajU3MnB0dE5DV3lpRVVVd3JDVVpnWFpwcXhtOVNDamlvMy8KYWgvK0FVc3luNkVEQ3RQWWhNK296WEdHZmk5aHRET2xvSWpLblNyOEVxWnYvQWxQclFVcjNhN2RzZTNIdkVUdQpsWnY5Y1RTTTN2UTQzeXFXbm1TWS9YS1IrN1lCcEJCUTQxc09UWmY3RTJMK3Z0WVJ4cXZxSHZMZ0VUc2tVZERNCjk2dGF2NUFhdzFWRExyMXJLRHVubVRGclJoczUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
apiVersion: v1
kind: Service
metadata:
  name: kine-example-apiserver
  namespace: default
  labels:
    api: kine-example-apiserver
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: kine-example-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kine-example-apiserver
  namespace: default
  labels:
    api: kine-example-apiserver
spec:
  selector:
    matchLabels:
      api: kine-example-apiserver
  replicas: 1
  template:
    metadata:
      labels:
        api: kine-example-apiserver
    spec:
      containers:
      - name: apiserver
        image: example.io/kine
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "127.0.0.1"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: "test"
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://non-exist-etcd-addr:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: kine-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kine-example-controller
  namespace: default
  labels:
    api: kine-example-controller
spec:
  selector:
    matchLabels:
      api: kine-example-controller
  replicas: 1
  template:
    metadata:
      labels:
        api: kine-example-controller
    spec:
      containers:
        - name: controller
          image: example.io/kine
          imagePullPolicy: IfNotPresent
          command:
            - "./controller-manager"
          args:
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 300Mi
      volumes:
        - name: apiserver-certs
          secret:
            secretName: kine-example
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: kine-example
  namespace: default
  labels:
    api: kine-example
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lJUzVUNFhKYUFRNm93RFFZSktvWklodmNOQVFFTEJRQXdiREVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURXJNQ2tHQTFVRUF3d2lhMmx1WlMxbGVHRnRjR3hsTFdObGNuUnBabWxqWVhSbExXRjFkR2h2CmNtbDBlVEFlRncweU1ERXdNVFF4TURBek5EQmFGdzB6TURFd01USXhNREF6TkRCYU1DTXhJVEFmQmdOVkJBTVQKR0d0cGJtVXRaWGhoYlhCc1pTNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUApBRENDQVFvQ2dnRUJBTCs5YlEzejBBZWdhdU0wNm1UNkFjcTJheWFJdWg0ZVE1clNwU3RZNWZFYm1xbHJQQ3RLCktNNVBQUUxNKy94UFhqaHRMcUNJaWtBNjBNbVp1eFI0QzZuNFQvT2dQSHo2S1llMzNhNnBrRzQ5WjF2aHhXSjYKT1lsMzQxS2JMV2krNjlIM2hzT3J1cDU2MFVBcjBrWHVDOFFuVWh3STNLTkFMc1lmNHJkRHl0VFhRVU40TGVrVwppbWlPeHpCY3Q5VWVERHYyQ3BrODU1Zk1LYU93ZkVPdjNTbzErL1A3NVR2bUFSWXFCRTEydDhIcEZPeHVkVnVOCjU0YkJMbXQzc2hNbXVsakZ3QVA3dzFOUWxka3BORjQwUy9TYlBzVWFxcFBPUS9VY0NFUFA0Yyt5QUNSRGYzMSsKa3cwK2EwdGJ3VTcrWmNrbFI4VTFQc1MxVUpGemdrVnloQU1DQXdFQUFhTmNNRm93RGdZRFZSMFBBUUgvQkFRRApBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQXBCZ05WSFJFRUlqQWdnaGhyCmFXNWxMV1Y0WVcxd2JHVXVaR1ZtWVhWc2RDNXpkbU9IQkg4QUFBRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUV0N25IMG03bUduM2hWY1Q4QTNUWndNeUR5QndiRGIxNEJmMTlLKzQ3L21aTVNUVFBHU1Q4ck9LeDJmNi9BRQpYNkNOR2JoWkV3REN3UlR4UjRDZkRmOFRNNlZISTBNN3p1WGFLNXlxSExtTE5QbUJaS3VOUTJCdXVHTUhkSFVzCk5jSnI3UnFxK21oRlhpbEE1MWtKREwwSE1JTytuVFYxVVBGSU5IbEx2WjF0Y0d0Y2crWVRYVFB1dmNoNE9ram8KWU16NE1mVFBkcE1FYU12Yk9vcEp6YVVSNGlJMW4wYWN5YjBGdDMwYjVkSFQzWE5DM0pabXJYS2FtSDFKY0E3TwpGdXFGTjc4dlR6ZmtiWDlWUjM1K3ZIWUtxY1c1cG1ZT2lBRG5USHdWK2JjcmJ1WVZsVmx5cmdobEhlTHdwc3l5CmRZYmxuRk9hNTZESlNoSDEzMzdWTjdNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdjcxdERmUFFCNkJxNHpUcVpQb0J5clpySm9pNkhoNURtdEtsSzFqbDhSdWFxV3M4Ckswb296azg5QXN6Ny9FOWVPRzB1b0lpS1FEclF5Wm03RkhnTHFmaFA4NkE4ZlBvcGg3ZmRycW1RYmoxblcrSEYKWW5vNWlYZmpVcHN0YUw3cjBmZUd3NnU2bm5yUlFDdlNSZTRMeENkU0hBamNvMEF1eGgvaXQwUEsxTmRCUTNndAo2UmFLYUk3SE1GeTMxUjRNTy9ZS21Uem5sOHdwbzdCOFE2L2RLalg3OC92bE8rWUJGaW9FVFhhM3dla1U3RzUxClc0M25oc0V1YTNleUV5YTZXTVhBQS92RFUxQ1YyU2swWGpSTDlKcyt4UnFxazg1RDlSd0lROC9oejdJQUpFTi8KZlg2VERUNXJTMXZCVHY1bHlTVkh4VFUreExWUWtYT0NSWEtFQXdJREFRQUJBb0lCQURBOXo3ZG45WnBGb1Q4RApMRW8xb01mSTk5S2RLZjZ6N0p5Q2pTNEgwdXJENERqcUV4eHRMekVoUEo5OHhaV292bk1CL1c1RWpFdzJ3QnRKCkE0blYzbEZvZVcwNWpwNS9MbjNJSkExeStqVFNYRFFBN1BHbkFOejJmZ3Bsb3BvdEZ4WWY2aGRIR05BUTVKNzUKcDVFU29JRTh4MnJvUytNREhnR1pPaWlUOU85eHZZTTd3UWlWSDdiK0JiNHVQbER6NTJmM2dZUXl0WVN5OFhjNApzNHh4YlhLYjVhQWE3MjMzMVlGWm9HWjJuRTd5VmIrY1IvVm9NV2NmOHQxOC9DZnpqTjJabVVzdUNQVWFFNTdjCk83dG9Sc01GRGN0QzlJU3l1cmJGK3VScjVKNG9WbVFjcGxOQlQ4SHYzMTZLN0VxbUoxYnVNbG1qTzNhZGhRaDYKMWdSM0Jna0NnWUVBMGZYSDRHa2RkUzl6MkNZRkVIRHU3dmlwYWpPTEJjaStVYk5DZklKRVRIUURsY29MVVVxVQpnRzRySnVQSFFreHArRDA0L09XZ3llck5NTjJkSHJNZS81N00rTmQ0clJHOFVZK0JQQndqWkFKNlQ0NU1QblJyCkJ6TGRUdWJnMk9CNjIwSzdKNldoMURqOUtodFNJRG8vT1oyRHNqZmFlRVM4N0ZmSFF2VGwzdDBDZ1lFQTZjaloKTFY5Vi81Z2dGNkx0WDhUbmpUd2N4UHJjUVd5Tm1hM3FkSDFUWU5TYklXYStrOVhoZHBQTGVyZEFLUGpCTVgxTApQblpUMmRIbUZHcVpCRnJ0UnR0Mzl1OEtuMWdmSll4WEpudXFYM3pTSVQ5MU8xVFNsSEJpUUduQzJVVTJQQzJECmhnQ0RnVEJqazZjVkp0Y0NyWGNyZ2lYYVFQT3VucW5NeitZakVGOENnWUJqU3JtQW5oVkpRdXlrN3EzOGJYd0IKVldWQkRTa1V6aTk3RWF4Q2w1UlhGNUpPZHlOTkNWa2JOMzUrd0wrTjBmZFhaeFNaUExzQ1ltRXhWOHlqSlJCbQowS0djbU1IQUR5QWc3aDJ1NEp1NEF4ZjJvWlBiQVZGUU1UVEp5SlBTM0s0ZEhQekhMaVJPNmJpSC9pMmpnZ2crClpnaE84dTBGYlhSdXpNQTJJUHpJblFLQmdRQ0o1TzQwMVFia3U5WXlHdWZvbFR2L0VuWGx1aEl3aE5jQXpwUjgKSVhBTXJWclRXTWNRYkJlUTJad3J4ZXNTUDZlMGlUTFlwUExRaC80dURMSTAzMjBWWGw1a1NKcjdZZjc5SnNwQQo2TENWb2dwUGtoNlQ0SFJWR2ZUYUNZZmtuKzVka0hzRGowb0I2WWpTanJyckxlZG1hZVEvNEJQY085L0R0bVFZClBLWnlBUUtCZ1FDOUg0LzFmQ3plZFE5UnIxYVlYNUY3ZGNma2dYYmFOejdUazNHSXdnTVJYenJrT09IMVNVTzQKU1lFVk5TeDBaMVBZd1ZvdnJkaHFtTHFVM1BsRDJaTnBQN2Y5MGJIQ21Sd2hMU1dTMGd3RFQyZXVZcTg2d2F2agpEM2ZqMFh6MmtkamFEUlpqc3VlSktwOFZkdDVPQzhFejF3bXV0eTZoRGlub3Qvd1hOeWdGR0E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extension-apiserver-authentication-reader
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-example-apiserver-auth-reader
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-example-apiserver-auth-reader
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-apiserver-auth-delegator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-example-controller
  namespace: default
rules:
  - apiGroups:
      - 'mysql.example.com'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: basic-example-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: basic-example-controller
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
